version: "3.3"

services:
  bytes:
    container_name: bytes
    build: .
    volumes:
      - $PWD:/bytes
    networks:
      bytes-dev:
        aliases:
          - bytes-host
    command: ["bash", "-c", "tail -f /dev/null"]
    depends_on: ["postgres"]
    ports:
      - 80:80
    environment:
      PGPASSWORD: password
      PGUSER: postgres
      PGPORT: 5432
      PGHOST: database-host
      PGDATABASE: bytes
      PORT: 80
  postgres:
    container_name: postgres
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    networks:
      bytes-dev:
        aliases:
          - database-host
  bytes-frontend:
    container_name: bytes-frontend
    build: $PWD/../bytes-frontend
    volumes:
      - $PWD/../bytes-frontend:/bytes-frontend
    networks:
      bytes-dev:
        aliases:
          - bytes-frontend-host
    command: ["bash", "-c", "tail -f /dev/null"]
    depends_on: ["bytes"]
    ports:
      - 810:80
    environment:
      URL: ip-address
      PORT: 80
      NODE_ENV: dev
networks:
  bytes-dev:
    external: false
