version: "3.3"

services:
  bytes:
    container_name: bytes
    build: .
    volumes:
      - $PWD:/bytes
    networks:
      bytes-dev:
        aliases:
          - bytes-host
    command: ["bash", "-c", "tail -f /dev/null"]
    depends_on: ["postgres"]
    ports:
      - 80:80
    environment:
      PGPASSWORD: password
      PGUSER: postgres
      PGPORT: 5432
      PGHOST: database-host
      PGDATABASE: bytes
      PORT: 80
      JWT_KEY: random
      URL: http://localhost/api
      AWS_SECRET_ACCESS_KEY: random
      AWS_ACCESS_KEY_ID: random
      BUCKET: random
      DOMAIN: random
      MAILGUN_KEY: random
      SLACK_HOOK_URL: random
      ENV: dev
  postgres:
    container_name: postgres
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    networks:
      bytes-dev:
        aliases:
          - database-host
networks:
  bytes-dev:
    external: false
