version: 2
jobs:
  test:
    docker:
      - image: circleci/node:7.10
        environment:
          PGHOST: 127.0.0.1
          PGUSER: postgres
          ENV: dev
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_DB: bytes
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - run: npm install npx

      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run test

workflows:
  version: 2
  test:
    jobs:
      - test
