version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
      - image: circleci/postgres:alpine

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm run install

      - run: ./bootstrap.sh

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run test

workflows:
  version: 2
  test:
    jobs:
      - build
