aliases:
  - &attach_workspace
    attach_workspace:
      at: .

  - &persist_to_workspace
    persist_to_workspace:
      root: .
      paths:
        - .
  - &restore_cache
    keys:
      - v1-dependencies-{{ checksum "package.json" }}
      - v1-dependencies-

  - &save_cache
    paths:
      - node_modules
    key: v1-dependencies-{{ checksum "package.json" }}

  - &filter-only-master
    branches:
      only:
        - master

# Build environment
defaults: &defaults
  working_directory:
  docker:
    - image: circleci/node:chakracore-10.13
      environment:
        PGPORT: 5432
        PGDATABASE: bytes
        PGUSER: postgres
        PGHOST: 127.0.0.1
        PGPASSWORD: password
        ENV: dev
        JWT_KEY: key
        PORT: 80
    - image: circleci/postgres:9.6.2-alpine
      environment:
        POSTGRES_DB: bytes
        POSTGRES_PASSWORD: password
        POSTGRES_USER: postgres

version: 2
jobs:
  "Install":
    <<: *defaults
    steps:
      - checkout
      - *attach_workspace
      # - restore_cache: *restore_cache
      - run: sudo apt-get install libpq-dev
      - run: npm install
      - run: npm install npx
      - save_cache: *save_cache
      - *persist_to_workspace
  "User Tests":
    <<: *defaults
    steps:
      - checkout
      - *attach_workspace
      - run: npx ts-node ./test/utils/setup-db.ts
      - run: npm run test-users
      - *persist_to_workspace
  "Byte Tests":
    <<: *defaults
    steps:
      - checkout
      - *attach_workspace
      - run: npx ts-node ./test/utils/setup-db.ts
      - run: npm run test-bytes
      - *persist_to_workspace
  "Unit Tests":
    <<: *defaults
    steps:
      - checkout
      - *attach_workspace
      - run: npm run test-unit
      - *persist_to_workspace
  "Publish Image":
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASS
      - run: echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
      - run: echo 'export IMAGE_NAME=bytes' >> $BASH_ENV
      - run: docker build -t boristane/$IMAGE_NAME:$TAG .
      - run: docker push boristane/$IMAGE_NAME:$TAG

workflows:
  version: 2
  test:
    jobs:
      - "Install"
      - "User Tests":
          requires:
            - "Install"
      - "Byte Tests":
          requires:
            - "User Tests"
      - "Unit Tests":
          requires:
            - "Install"
      - "Publish Image":
          requires:
            - User Tests
            - Byte Tests
            - Unit Tests
          filters: *filter-only-master
